const GET_LIST_OF_RSS_CHANNELS = 'GET_LIST_OF_RSS_CHANNELS';
const GET_LIST_OF_RSS_CHANNELS_SUCCEEDED = 'GET_LIST_OF_RSS_CHANNELS_SUCCEEDED';
const GET_LIST_OF_RSS_CHANNELS_FAILED = 'GET_LIST_OF_RSS_CHANNELS_FAILED';

const GET_LIST_OF_ENTRIES = 'GET_LIST_OF_ENTRIES';
const GET_LIST_OF_ENTRIES_SUCCEEDED = 'GET_LIST_OF_ENTRIES_SUCCEEDED';
const GET_LIST_OF_ENTRIES_FAILED = 'GET_LIST_OF_ENTRIES_FAILED';


const SHOW_ENTRY_CONTENTS = 'SHOW_ENTRY_CONTENTS';
const SHOW_ENTRY_CONTENTS_SUCCEEDED = 'SHOW_ENTRY_CONTENTS_SUCCEEDED';
const SHOW_ENTRY_CONTENTS_FAILED = 'SHOW_ENTRY_CONTENTS_FAILED';


const MARK_AS_FAVORITE = 'MARK_AS_FAVORITE';
const SHOW_LIST_OF_FAVORITE='SHOW_LIST_OF_FAVORITE';