export const GET_LIST_OF_RSS_CHANNELS = 'GET_LIST_OF_RSS_CHANNELS';
export const GET_LIST_OF_RSS_CHANNELS_SUCCEEDED = 'GET_LIST_OF_RSS_CHANNELS_SUCCEEDED';
export const GET_LIST_OF_RSS_CHANNELS_FAILED = 'GET_LIST_OF_RSS_CHANNELS_FAILED';

export const GET_LIST_OF_ENTRIES = 'GET_LIST_OF_ENTRIES';
export const GET_LIST_OF_ENTRIES_SUCCEEDED = 'GET_LIST_OF_ENTRIES_SUCCEEDED';
export const GET_LIST_OF_ENTRIES_FAILED = 'GET_LIST_OF_ENTRIES_FAILED';


export const SHOW_ENTRY_CONTENTS = 'SHOW_ENTRY_CONTENTS';
export const SHOW_ENTRY_CONTENTS_SUCCEEDED = 'SHOW_ENTRY_CONTENTS_SUCCEEDED';
export const SHOW_ENTRY_CONTENTS_FAILED = 'SHOW_ENTRY_CONTENTS_FAILED';


export const MARK_AS_FAVORITE = 'MARK_AS_FAVORITE';
export const SHOW_LIST_OF_FAVORITE='SHOW_LIST_OF_FAVORITE';